name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run bun:build && bun run build:bin

      - name: Publish to NPM
        run: bun publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Library Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Library Release ${{ github.ref_name }}"
          files: |
            dist/index.js
            dist/index.d.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Binary Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Binary Release ${{ github.ref_name }}"
          files: |
            dist/striped
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
